### ISSUE TITLE
SLR2 - Heating & Water

### ISSUE THREAD

**Issue by jonwilliams84** [greeeny101/Hive-Thermostat-Zigbee2MQTT#3]
Hi, I am trying to get this working with the SLR2 which controls both heating and water. 

This is the json payload I see in the heating topic:

```json
{
  "linkquality":43,
  "local_temperature_heat":20.64,
  "occupied_heating_setpoint":18,
  "occupied_heating_setpoint_heat":18,
  "running_state_heat":"idle",
  "running_state_water":"heat",
  "system_mode":"heat",
  "system_mode_heat":"off",
  "system_mode_water":"emergency_heating",
  "temperature_setpoint_hold_duration_heat":65535,
  "temperature_setpoint_hold_duration_water":65535,
  "temperature_setpoint_hold_heat":true,
  "temperature_setpoint_hold_water":true
}
```

Any chance you could assist with the changes / additional sensors & automations that need to be made.

Thank you in advance

**Comment by jonwilliams84** [comment]
Ok, After a bit of playing I have got it working with the SLR2 device. I still haven't worked out how to control the water from the same simple thermostat card as the heating but have got around that by adding an input_button that triggers an automation making the mqtt publish service call to toggle water on and off.

Also for some reason, my thermostat reports the temperature and set temperature of the water, but as I have a system boiler I have no idea where its getting this value from (21C) and when its on its (22C).

I have also added a simple timer that starts when 'Boost' is set and gives you a countdown on the card as a visual aid.

To get this running I have created a package yaml for hive.

configuration.yaml
```yaml
homeassistant:
  packages:
    hive: !include hive.yaml
```

hive.yaml
```yaml
mqtt:
  sensor:
    - unique_id: "heating_local_temperature_heat"
      name: "Heating Local temperature Heating"
      state_topic: "zigbee2mqtt/heating"
      value_template: "{{ value_json.local_temperature_heat | round(1, 'floor') }}"
      force_update: true

    - unique_id: "heating_occupied_heating_setpoint_heat"
      name: "Heating Occupied Heating Setpoint Heating"
      state_topic: "zigbee2mqtt/heating"
      unit_of_measurement: "°C"
      value_template: "{{ value_json.occupied_heating_setpoint_heat }}"
      force_update: true

    - unique_id: "heating_system_mode_heat"
      name: "Heating System Mode Heating"
      state_topic: "zigbee2mqtt/heating"
      value_template: "{{ value_json.system_mode_heat }}"
      force_update: true

    - unique_id: "heating_running_state_heat"
      name: "Heating Running State Heating"
      state_topic: "zigbee2mqtt/heating"
      value_template: "{{ value_json.running_state_heat }}"
      force_update: true

    - unique_id: "heating_temperature_setpoint_hold_heat"
      name: "Heating Temperature Setpoint Hold Heating"
      state_topic: "zigbee2mqtt/heating"
      force_update: true
      value_template: "{{ value_json.temperature_setpoint_hold_heat }}"

    - unique_id: "heating_local_temperature_water"
      name: "Heating Local temperature Water"
      state_topic: "zigbee2mqtt/heating"
      value_template: "{{ value_json.local_temperature_water | round(1, 'floor') }}"
      force_update: true

    - unique_id: "heating_occupied_heating_setpoint_water"
      name: "Heating Occupied Heating Setpoint Water"
      state_topic: "zigbee2mqtt/heating"
      unit_of_measurement: "°C"
      value_template: "{{ value_json.occupied_heating_setpoint_water }}"
      force_update: true

    - unique_id: "heating_system_mode_water"
      name: "Heating System Mode Water"
      state_topic: "zigbee2mqtt/heating"
      value_template: "{{ value_json.system_mode_water }}"
      force_update: true

    - unique_id: "heating_running_state_water"
      name: "Heating Running State Water"
      state_topic: "zigbee2mqtt/heating"
      value_template: "{{ value_json.running_state_water }}"
      force_update: true

    - unique_id: "heating_temperature_setpoint_hold_water"
      name: "Heating Temperature Setpoint Hold Water"
      state_topic: "zigbee2mqtt/heating"
      force_update: true
      value_template: "{{ value_json.temperature_setpoint_hold_water }}"

  climate:
    unique_id: "heating_proxy"
    name: Heating Proxy
    max_temp: 32
    min_temp: 12
    precision: 0.5
    retain: false
    qos: 0
    payload_on: 1
    payload_off: 0
    temperature_unit: "C"
    modes:
      - "auto"
      - "off"
      - "heat"
      - "cool"
  
    # Listen for changes published by the thermostat
  
    mode_state_topic: "zigbee2mqtt/heating"
    mode_state_template: >-
      {% if value_json.system_mode_heat == 'heat' and
        value_json.temperature_setpoint_hold_duration_heat !=65535
      %}
        auto
      {% elif value_json.system_mode_heat == 'emergency_heating' %}
        cool
      {% elif value_json.system_mode_heat == 'heat' and
        value_json.temperature_setpoint_hold_duration_heat == 65535
      %}
        heat
      {% elif value_json.system_mode_heat == 'off'%}
        off
      {% endif %}
  
    current_temperature_topic: "zigbee2mqtt/heating"
    current_temperature_template: "{{value_json.local_temperature_heat}}"
  
    temperature_state_topic: "zigbee2mqtt/heating"
    temperature_state_template: >-
      {% if value_json.occupied_heating_setpoint_heat != 1 %}
        {{value_json.occupied_heating_setpoint_heat}}
      {% elif states("sensor.heating_system_mode_heat") == "off" %}
        {{states("input_number.heating_frost_prevention")}}
      {% elif states("sensor.heating_system_mode_heat") == "heat" and
        states("sensor.heating_temperature_setpoint_hold_duration_heat") != 65536
      %}
        {{states("input_number.heating_frost_prevention")}}
      {% endif %}
  
    # get changes in the climate component and republish on the topic
    # (Rather than going directly to the thermostat)
  
    temperature_command_topic: "zigbee2mqtt/heating_proxy/occupied_heating_setpoint"
    mode_command_topic: "zigbee2mqtt/heating_proxy/system_mode"

input_number:
  heating_manual_default:
    name: Heating Default Temperature
    initial: 18.5
    min: 16
    max: 20
    step: 0.5

  heating_boost_temperature:
    name: Heating Boost Temperature
    initial: 25
    min: 12
    max: 32
    step: 0.5
    icon: "mdi:heat-wave"
    mode: slider
  
  heating_frost_prevention:
    name: Heating Frost Prevention
    initial: 12
    min: 5
    max: 16
    step: 0.5
    icon: "mdi:snowflake-thermometer"
  
  heating_boost_duration:
    name: Heating Boost Duration
    initial: 30
    min: 5
    max: 60
    step: 5
    icon: "mdi:timer"
    mode: slider

input_button:
  hot_water:
    name: Hot Water
    icon: mdi:water

timer:
  heating_boost_duration:
    name: Boost remaining
    duration: 254

automation:
  - id: '1666548062412'
    alias: 'Heating Set Temperature'
    description: 'Sends the requested temperature from the climate control to the correct topic'
    trigger:
    - platform: mqtt
      topic: zigbee2mqtt/heating_proxy/occupied_heating_setpoint
    condition:
    - condition: template
      value_template: '{{trigger.payload != 1}}'
    action:
    - choose:
      - conditions:
        - condition: template
          value_template: "{{ states('sensor.heating_system_mode_heating') == 'heat'}}"
        sequence:
        - service: mqtt.publish
          data:
            topic: zigbee2mqtt/heating/set
            payload_template: '{"occupied_heating_setpoint_heat":"{{trigger.payload}}"}' 
      - conditions:
        - condition: template
          value_template: "{{ states('sensor.heating_system_mode_heating') == 'off'}}"
        sequence:
        - service: mqtt.publish
          data:
            topic: zigbee2mqtt/heating/set
            payload_template: '{"temperature_setpoint_hold_heat":"1", "system_mode":"heat" }'
        - delay: 0.5
        - service: mqtt.publish
          data:
            topic: zigbee2mqtt/heating/set
            payload_template: '{
              "temperature_setpoint_hold_heat":"1",
              "system_mode_heat":"heat",
              "occupied_heating_setpoint_heat":{{trigger.payload}}
            }'
    mode: single 
      
  - id: '1666513667863'
    alias: 'Heating System Mode'
    description: 'Sends the requested system mode from the climate control to the correct topic'
    trigger:
    - platform: mqtt
      topic: zigbee2mqtt/heating_proxy/system_mode
      id: system mode
    condition: []
    action:
    - choose:
      - conditions:
        - condition: template
          value_template: '{{ trigger.payload == "off" }} '
        sequence:
        - service: mqtt.publish
          data:
            topic: zigbee2mqtt/heating/set
            payload_template: '{
              "system_mode_heat":"off",
              "temperature_setpoint_hold_heat":"0"
            }'
        - delay: 0.5
        - service: mqtt.publish
          data:
            topic: zigbee2mqtt/heating/set
            payload_template: '{
              "occupied_heating_setpoint_heat":{{states("input_number.heating_frost_prevention")}},
              "temperature_setpoint_hold_heat":"1"
              "temperature_setpoint_hold_duration_heat":"65535"
            }'
  
      - conditions:
        - condition: template
          value_template: '{{ trigger.payload == "heat" and states("sensor.occupied_heating_setpoint") != 1}}'
        sequence:
        - service: mqtt.publish
          data:
            topic: zigbee2mqtt/heating/set
            payload_template: '{
              "occupied_heating_setpoint_heat":{{states("input_number.heating_manual_default")}},
              "temperature_setpoint_hold":"1",
              "system_mode_heat":"heat",
              "temperature_setpoint_hold_duration_heat":"65535"
            }'
  
      - conditions:
        - condition: template
          value_template: '{{ trigger.payload == "cool" and states("sensor.occupied_heating_setpoint") != 1}}'
        sequence:
        - service: mqtt.publish
          data:
            topic: zigbee2mqtt/heating/set
            payload_template: '{
              "temperature_setpoint_hold_heat":"1",
              "system_mode_heat":"emergency_heating",
              "occupied_heating_setpoint_heat":{{states("input_number.heating_boost_temperature")}},
              "temperature_setpoint_hold_duration_heat":{{states("input_number.heating_boost_duration")}} 
            }'
        - delay: 0.5
        - service: mqtt.publish
          data:
            topic: zigbee2mqtt/heating/set
            payload_template: '{
              "temperature_setpoint_hold_heat":"1",
              "system_mode_heat":"emergency_heating",
              "occupied_heating_setpoint_heat":{{states("input_number.heating_boost_temperature")}},
              "temperature_setpoint_hold_duration_heat":{{states("input_number.heating_boost_duration")}} 
            }'
        - service: timer.start
          entity_id: timer.heating_boost_duration
          data_template:
            duration: "{{ '00:0%i:00' % (states('input_number.heating_boost_duration') | int ) }}"  
      - conditions:
        - condition: template
          value_template: '{{ trigger.payload == "auto" }}'
        sequence:
        - service: mqtt.publish
          data:
            topic: zigbee2mqtt/heating/set
            payload_template: '{
              "system_mode_heat":"auto",
              "temperature_setpoint_hold_heat":"0"
            }'  
    mode: single
  - id: '166651366456'
    alias: Heating Hot Water
    description: ""
    trigger:
      - platform: state
        entity_id:
          - input_button.hot_water
    condition: []
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: sensor.heating_running_state_water
                state: heat
            sequence:
              - service: mqtt.publish
                data:
                  topic: zigbee2mqtt/heating/set
                  payload: >-
                    {    "system_mode_water":"off",   
                    "temperature_setpoint_hold_water":"0" }
          - conditions:
              - condition: state
                entity_id: sensor.heating_system_mode_water
                state: "off"
            sequence:
              - service: mqtt.publish
                data:
                  topic: zigbee2mqtt/heating/set
                  payload: >-
                    {    "system_mode_water":"heat",   
                    "temperature_setpoint_hold_water":"1" }
    mode: single
```

And my card(s) look like this:
<img width="497" alt="image" src="https://user-images.githubusercontent.com/24478629/210838494-e21c25ae-31ea-40eb-aba9-eef55cbd3a6c.png">

Card:
```yaml
type: vertical-stack
cards:
  - type: custom:simple-thermostat
    entity: climate.heating_proxy
    hide:
      temperature: true
      state: true
    sensors:
      - entity: sensor.heating_local_temperature
        icon: mdi:home-thermometer-outline
        unit: ' °C'
      - entity: sensor.heating_running_state
        icon: mdi:fire
      - entity: sensor.heating_running_state_water
        icon: mdi:water
    layout:
      mode:
        headings: false
        icons: true
        names: true
    control:
      hvac:
        auto:
          name: Schedule
        cool:
          name: Boost
          icon: mdi:heat-wave
    header:
      name: Heating
  - type: custom:mushroom-climate-card
    entity: climate.heating_water
    fill_container: false
    name: Hot Water
    primary_info: name
    icon: mdi:thermometer-water
    show_temperature_control: false
    collapsible_controls: false
    tap_action:
      action: call-service
      service: input_button.press
      data: {}
      target:
        entity_id: input_button.hot_water
    hold_action:
      action: more-info
    secondary_info: none
  - type: entities
    entities:
      - entity: input_number.heating_boost_temperature
        name: Boost Temperature
      - entity: input_number.heating_boost_duration
        name: Boost Duration
      - entity: timer.heating_boost_duration
        name: Boost Remaining
      - entity: sensor.thermostat_battery
```

**Comment by greeeny101** [comment]
@jonwilliams84  Glad to see you've managed to get up and running. Is this your thermostat ? https://www.zigbee2mqtt.io/devices/SLR2.html
If so, I've noticed it uses two endpoints  name/heat/set or name/water/set, so is it possible to hook up another climate/thermostat card and point it to the endpoint for the water.
The temperature that's slightly out, do you need to change this "{{ value_json.local_temperature_water | round(1, 'floor') }}" to "ceil" as it's rounding down at the moment

I've been thinking of adding a countdown to my config for a while, I'll take your config for that and update if that's ok.

The other thing I've been thinking is replacing the boost temperature with a 'degrees above the current temperature' number instead. so if the local temperature is 17 degrees I just want to boost to 0.5, 1, 1.5 etc above that.

**Comment by jonwilliams84** [comment]
> @jonwilliams84 Glad to see you've managed to get up and running. Is this your thermostat ? https://www.zigbee2mqtt.io/devices/SLR2.html If so, I've noticed it uses two endpoints name/heat/set or name/water/set, so is it possible to hook up another climate/thermostat card and point it to the endpoint for the water. The temperature that's slightly out, do you need to change this "{{ value_json.local_temperature_water | round(1, 'floor') }}" to "ceil" as it's rounding down at the moment
> 
> I've been thinking of adding a countdown to my config for a while, I'll take your config for that and update if that's ok.
> 
> The other thing I've been thinking is replacing the boost temperature with a 'degrees above the current temperature' number instead. so if the local temperature is 17 degrees I just want to boost to 0.5, 1, 1.5 etc above that.

I could add water to an additional climate card, but I would prefer not to.  I think I could maybe use `aux_*` , `swing_mode` or even `fan_mode` in the MQTT HVAC integration for hot_water, but would need to have another play.

As I have a system boiler, not combi, hot water is provided by a high pressure tank and immersion heater.  So hot water is either on/off or on schedule. Generally we leave this on permanently anyway.

To change the boost temperature to a delta of current temperature is dead easy:

Create a template sensor that in the example below adds 1.5 to the local temp, rounds to the nearest *.5 or *.0 and validates the result is below 32C (if it's above then it sets the state to 32C).

Then just return that sensor in the boost mqtt statement instead of the input number.

```yaml
template:
  - sensor:
    - name: "Heating Boost Temperature"
      unique_id: heating_boost_temperature
      device_class: temperature
      unit_of_measurement: "C"
      state_class: "measurement"
      state: >
       {% if states('sensor.heating_local_temperature') | float + 1.5 | round(1, 'half', 0) < 32.0 %}
          {% set boost_temp = (states('sensor.heating_local_temperature') | float + 1.5) | round(1, 'half', 0) %} 
       {% else %}
         {% set boost_temp = 32.0 %} 
       {% endif %}
       {{ (boost_temp) }}
```

If I get chance this weekend I may have a play with aux/fan/swing to see if it will achieve what I want, namely a single card.

**Comment by jonwilliams84** [comment]
Was easier than I thought. Here we go:

Added this to the mqtt climate integration:
```yaml
    swing_mode_state_topic: "zigbee2mqtt/heating"
    swing_mode_state_template: >-
      {% if value_json.system_mode_water == 'heat' and
        value_json.temperature_setpoint_hold_duration_water !=65535
      %}
        auto
      {% elif value_json.system_mode_water == 'heat' and
        value_json.temperature_setpoint_hold_duration_water == 65535
      %}
        heat
      {% elif value_json.system_mode_water == 'off'%}
        off
      {% endif %}
    swing_modes: 
      - "off"
      - "heat"
      - "auto"
    swing_mode_command_topic: "zigbee2mqtt/heating_proxy/system_mode_water"
```

Added this automation:
```yaml
  - id: '1666513607863'
    alias: 'Heating System Mode Water'
    description: 'Sends the requested system mode from the climate control to the correct topic'
    trigger:
    - platform: mqtt
      topic: zigbee2mqtt/heating_proxy/system_mode_water
      id: system mode water
    condition: []
    action:
    - choose:
      - conditions:
        - condition: template
          value_template: '{{ trigger.payload == "off" }} '
        sequence:
        - service: mqtt.publish
          data:
            topic: zigbee2mqtt/heating/set
            payload_template: '{
              "system_mode_water":"off",
              "temperature_setpoint_hold_water":"0"
            }'
  
      - conditions:
        - condition: template
          value_template: '{{ trigger.payload == "heat" and states("sensor.occupied_heating_setpoint_water") != 1}}'
        sequence:
        - service: mqtt.publish
          data:
            topic: zigbee2mqtt/heating/set
            payload_template: '{
              "temperature_setpoint_hold_water":"1",
              "system_mode_water":"heat"
            }'
  
      - conditions:
        - condition: template
          value_template: '{{ trigger.payload == "auto" }}'
        sequence:
        - service: mqtt.publish
          data:
            topic: zigbee2mqtt/heating/set
            payload_template: '{
              "system_mode_water":"auto",
              "temperature_setpoint_hold_water":"0"
            }'  
    mode: single
```

and updated the simple thermostat  card:
```yaml
type: custom:simple-thermostat
entity: climate.heating_proxy
hide:
  temperature: true
  state: true
sensors:
  - entity: sensor.heating_local_temperature
    icon: mdi:home-thermometer-outline
    unit: ' °C'
  - entity: climate.heating_heat
    icon: mdi:function
  - entity: sensor.heating_running_state
    icon: mdi:fire
  - entity: climate.heating_water
    attribute: hvac_action
    icon: mdi:thermometer-water
layout:
  mode:
    headings: false
    icons: true
    names: true
control:
  hvac:
    auto:
      name: Schedule
    cool:
      name: Boost
      icon: mdi:heat-wave
    dry: null
  swing:
    auto:
      name: Schedule
    heat:
      name: Water
      icon: mdi:thermometer-water
header:
  name: Heating
```

And the result:
![image](https://user-images.githubusercontent.com/24478629/211116065-80077b32-cdf4-49a8-8791-79e12832424b.png)
